site_name: High Stakes  🇨🇭 Resources
repo_url: https://github.com/HighStakesSwitzerland/docs
site_description: Staking services with professional quality.
edit_uri: edit/main/docs/

dev_addr: 0.0.0.0:8000

nav:
  - Who We Are: 'index.md'
  - IBEX Loyalty Program:
      - Introduction: 'loyalty-program/index.md'
      - Registering: 'loyalty-program/register.md'
      - Redeeming: 'loyalty-program/redeem.md'
      - Linking Wallets: 'loyalty-program/link.md'
  - Staking Guides:
    - Terra: 'delegating/terra.md'
    - Injective: 'delegating/injective.md'
    - Secret Network: 'delegating/secretnetwork.md'
  - Auto-compounding: 'autocompound.md'
#  - Issue Tracker: 'https://status.highstakes.ch/'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - meta
  - tables

extra_css:
  - css/extra.css
